version: '2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.test
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    volumes:
      - ./web:/app
    environment:
      - API_URL=http://${API_SERVER_HOST}:${API_SERVER_PORT}/
