version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - "./api:/app"
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    depends_on:
      - mongo
  mongo:
    command: mongod
    image: mongo:4.0.4
    ports:
      - "27100:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
